# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Nika' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Nika
  pod 'SDWebImage'
  pod 'JGProgressHUD'
  
  # Facebook
  pod 'FBSDKShareKit', '~> 4.38.0'
  pod 'FBSDKCoreKit', '~> 4.38.0'
  pod 'FBSDKLoginKit', '~> 4.38.0'
  pod 'GoogleSignIn', '~> 4.4.0'
  
  # Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Firestore’
  pod 'Firebase/Auth’
  pod 'Firebase/Storage’
  pod 'Firebase/DynamicLinks'
  
  #  Crop and resize image
  pod 'CropViewController'
  
  #  Folding cell
  pod 'FoldingCell'
  
  pod 'ApiAI/Core'
  pod 'Crashlytics'
  
  #  Messenger
  pod 'Firebase/Database'
  pod 'OneSignal', '2.6.2'
  pod 'Realm'
  pod 'SinchRTC'
  pod 'SinchVerification'
  
  pod 'MBProgressHUD'
  pod 'MGSwipeTableCell'
  pod 'NYTPhotoViewer', '1.2.0'
  pod 'ProgressHUD'
  pod 'Reachability'
  pod 'RNCryptor-objc'
  pod 'SoundManager'
  pod 'AlamofireImage'

  target 'NikaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NikaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
